--[[
--Created Date: Saturday July 29th 2023 8:26:32 pm CEST
--Author: Trendon Robinson at <The_Pr0fessor (Rbx), @TPr0fessor (Twitter)>
-------
--Last Modified: Friday August 4th 2023 6:36:13 pm CEST
--Modified By: Trendon Robinson at <The_Pr0fessor (Rbx), @TPr0fessor (Twitter)>
--]]

export type TowerStats = {
	lastAttack: number,
	Position: Vector3,
	HP: number,
	armor: number,
	cost: number,
	damage: number,
	damageType: string,
	fireRate: number,
	level: number,
	range: number,
	sellValue: number,
	specialAbilities: string,
	splashArea: number,
	targetPriority: string,
	upgradePath: any,
}
local towerStats = {
	Pistol17 = {
		cost = 100,
		range = 3,
		damage = 20,
		fireRate = 5,
		damageType = "physical",
		specialAbilities = nil,
		HP = 100,
		armor = 10,
		sellValue = 50,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	MachineGun01 = {
		cost = 100,
		range = 3,
		damage = 20,
		fireRate = 5,
		damageType = "physical",
		specialAbilities = nil,
		HP = 100,
		armor = 10,
		sellValue = 50,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	MachineGun02 = {
		cost = 200,
		range = 3.5,
		damage = 25,
		fireRate = 5.5,
		damageType = "physical",
		specialAbilities = nil,
		HP = 120,
		armor = 12,
		sellValue = 100,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	WoodenSword = {
		cost = 50,
		range = 1,
		damage = 10,
		fireRate = 2,
		damageType = "physical",
		specialAbilities = nil,
		HP = 80,
		armor = 8,
		sellValue = 25,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	VikingShield = {
		cost = 75,
		range = 1,
		damage = 5,
		fireRate = 2,
		damageType = "physical",
		specialAbilities = "block",
		HP = 200,
		armor = 20,
		sellValue = 35,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "strongest",
		level = 1,
	},
	PirateCannon = {
		cost = 500,
		range = 5,
		damage = 100,
		fireRate = 1,
		damageType = "explosive",
		specialAbilities = "splash",
		HP = 150,
		armor = 15,
		sellValue = 250,
		upgradePath = nil,
		splashArea = 2,
		targetPriority = "nearest",
		level = 1,
	},
	Axe02 = {
		cost = 120,
		range = 1.5,
		damage = 30,
		fireRate = 2.5,
		damageType = "physical",
		specialAbilities = nil,
		HP = 110,
		armor = 11,
		sellValue = 60,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	VikingAxe = {
		cost = 120,
		range = 1.5,
		damage = 30,
		fireRate = 2.5,
		damageType = "physical",
		specialAbilities = nil,
		HP = 110,
		armor = 11,
		sellValue = 60,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	TNTBarrel = {
		cost = 400,
		range = 5,
		damage = 200,
		fireRate = 5,
		damageType = "explosive",
		specialAbilities = "detonate",
		HP = 100,
		armor = 5,
		sellValue = 200,
		upgradePath = nil,
		splashArea = 3,
		targetPriority = "nearest",
		level = 1,
	},
	Sword09 = {
		cost = 130,
		range = 1.2,
		damage = 35,
		fireRate = 3,
		damageType = "physical",
		specialAbilities = nil,
		HP = 90,
		armor = 10,
		sellValue = 65,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Sword08 = {
		cost = 120,
		range = 1.2,
		damage = 30,
		fireRate = 3,
		damageType = "physical",
		specialAbilities = nil,
		HP = 90,
		armor = 10,
		sellValue = 60,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Sword07 = {
		cost = 110,
		range = 1.2,
		damage = 25,
		fireRate = 3,
		damageType = "physical",
		specialAbilities = nil,
		HP = 90,
		armor = 10,
		sellValue = 55,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Sword06 = {
		cost = 100,
		range = 1.2,
		damage = 20,
		fireRate = 3,
		damageType = "physical",
		specialAbilities = nil,
		HP = 90,
		armor = 10,
		sellValue = 50,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Sword05 = {
		cost = 90,
		range = 1.2,
		damage = 15,
		fireRate = 3,
		damageType = "physical",
		specialAbilities = nil,
		HP = 90,
		armor = 10,
		sellValue = 45,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Cannonball = {
		cost = 150,
		range = 4,
		damage = 60,
		fireRate = 1,
		damageType = "explosive",
		specialAbilities = "splash",
		HP = 100,
		armor = 10,
		sellValue = 75,
		upgradePath = nil,
		splashArea = 2,
		targetPriority = "nearest",
		level = 1,
	},
	BombBarrel = {
		cost = 300,
		range = 5,
		damage = 150,
		fireRate = 5,
		damageType = "explosive",
		specialAbilities = "detonate",
		HP = 80,
		armor = 5,
		sellValue = 150,
		upgradePath = nil,
		splashArea = 2.5,
		targetPriority = "nearest",
		level = 1,
	},
	Knife06 = {
		cost = 60,
		range = 1,
		damage = 12,
		fireRate = 3,
		damageType = "physical",
		specialAbilities = nil,
		HP = 70,
		armor = 7,
		sellValue = 30,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Rifle13 = {
		cost = 250,
		range = 4,
		damage = 40,
		fireRate = 4,
		damageType = "physical",
		specialAbilities = nil,
		HP = 120,
		armor = 12,
		sellValue = 125,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	BoneKnife03 = {
		cost = 40,
		range = 1,
		damage = 8,
		fireRate = 2.5,
		damageType = "physical",
		specialAbilities = nil,
		HP = 60,
		armor = 6,
		sellValue = 20,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Rifle11 = {
		cost = 230,
		range = 4,
		damage = 38,
		fireRate = 4,
		damageType = "physical",
		specialAbilities = nil,
		HP = 120,
		armor = 12,
		sellValue = 115,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Rifle10 = {
		cost = 220,
		range = 4,
		damage = 36,
		fireRate = 4,
		damageType = "physical",
		specialAbilities = nil,
		HP = 120,
		armor = 12,
		sellValue = 110,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Shield02 = {
		cost = 100,
		range = 1,
		damage = 6,
		fireRate = 2,
		damageType = "physical",
		specialAbilities = "block",
		HP = 220,
		armor = 22,
		sellValue = 50,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "strongest",
		level = 1,
	},
	Sword04 = {
		cost = 80,
		range = 1.2,
		damage = 12,
		fireRate = 3,
		damageType = "physical",
		specialAbilities = nil,
		HP = 80,
		armor = 10,
		sellValue = 40,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Knife05 = {
		cost = 55,
		range = 1,
		damage = 10,
		fireRate = 3,
		damageType = "physical",
		specialAbilities = nil,
		HP = 65,
		armor = 7,
		sellValue = 27,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	BoneKnife02 = {
		cost = 35,
		range = 1,
		damage = 6,
		fireRate = 2.5,
		damageType = "physical",
		specialAbilities = nil,
		HP = 55,
		armor = 6,
		sellValue = 17,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	BoneKnife01 = {
		cost = 35,
		range = 1,
		damage = 6,
		fireRate = 2.5,
		damageType = "physical",
		specialAbilities = nil,
		HP = 55,
		armor = 6,
		sellValue = 17,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	CannonBall02 = {
		cost = 180,
		range = 4,
		damage = 70,
		fireRate = 1,
		damageType = "explosive",
		specialAbilities = "splash",
		HP = 100,
		armor = 10,
		sellValue = 90,
		upgradePath = nil,
		splashArea = 2.2,
		targetPriority = "nearest",
		level = 1,
	},
	Bow01 = {
		cost = 180,
		range = 4,
		damage = 70,
		fireRate = 1,
		damageType = "explosive",
		specialAbilities = "splash",
		HP = 100,
		armor = 10,
		sellValue = 90,
		upgradePath = nil,
		splashArea = 2.2,
		targetPriority = "nearest",
		level = 1,
	},
	BombBarrel02 = {
		cost = 350,
		range = 5,
		damage = 170,
		fireRate = 5,
		damageType = "explosive",
		specialAbilities = "detonate",
		HP = 85,
		armor = 5,
		sellValue = 175,
		upgradePath = nil,
		splashArea = 2.8,
		targetPriority = "nearest",
		level = 1,
	},
	MachineGun03 = {
		cost = 300,
		range = 3.8,
		damage = 30,
		fireRate = 6,
		damageType = "physical",
		specialAbilities = nil,
		HP = 140,
		armor = 14,
		sellValue = 150,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
	Rifle09 = {
		cost = 210,
		range = 4,
		damage = 34,
		fireRate = 4,
		damageType = "physical",
		specialAbilities = nil,
		HP = 115,
		armor = 12,
		sellValue = 105,
		upgradePath = nil,
		splashArea = nil,
		targetPriority = "nearest",
		level = 1,
	},
}

return towerStats
